const translateCertifictes = {
    JSFrontEndInfo: {
        bg: "В курса по JavaScript научих основите на езика и как да манипулирам данни с променливи, функции и условни изрази. Разгледах също цикли, масиви и обекти, и как да работя с тях в реални приложения. Също така изучих асинхронно програмиране с помощта на промиси и async/await, както и как да работя с DOM (Document Object Model), за да взаимодействам с уеб страниците. Научих се да създавам динамични уеб приложения, които могат да взаимодействат с потребителя и да обновяват съдържанието без презареждане на страницата.",
        de: "Im JavaScript-Kurs habe ich die Grundlagen der Sprache gelernt und wie man mit Variablen, Funktionen und bedingten Ausdrücken Daten manipuliert. Ich habe auch Schleifen, Arrays und Objekte untersucht und gelernt, wie man mit ihnen in realen Anwendungen arbeitet. Zudem habe ich asynchrones Programmieren mit Promises und async/await sowie den Umgang mit dem DOM (Document Object Model) gelernt, um mit Webseiten zu interagieren. Ich habe gelernt, dynamische Webanwendungen zu erstellen, die mit dem Benutzer interagieren und den Inhalt ohne ein Neuladen der Seite aktualisieren.",
        en: "In the JavaScript course, I learned the basics of the language and how to manipulate data using variables, functions, and conditional statements. I also explored loops, arrays, and objects, and how to work with them in real-world applications. Additionally, I studied asynchronous programming using promises and async/await, as well as how to work with the DOM (Document Object Model) to interact with web pages. I learned how to create dynamic web applications that can interact with users and update content without reloading the page."
      },
    htmlCssInfo: {
        bg: "В курса по HTML и CSS изучих основите на типографията и как да стилизирам уеб сайтове с помощта на CSS. Работих върху изграждането на уеб страници, като създавах адаптивен (responsive) уеб дизайн, който гарантира правилно визуализиране на съдържанието на различни устройства. Курсът ме запозна с техниките за създаване на съвременни уеб сайтове и ми даде възможност да създавам статични уеб страници, които са добре структурирани и визуално привлекателни.",
        de: "Im HTML- und CSS-Kurs habe ich die Grundlagen der Typografie gelernt und wie man Websites mit CSS stylt. Ich habe an der Erstellung von Webseiten gearbeitet und responsive Webdesigns entwickelt, die eine korrekte Darstellung des Inhalts auf verschiedenen Geräten gewährleisten. Der Kurs hat mir Techniken zur Erstellung moderner Websites beigebracht und mir die Möglichkeit gegeben, statische Webseiten zu erstellen, die gut strukturiert und visuell ansprechend sind.",
        en: "In the HTML and CSS course, I learned the basics of typography and how to style websites using CSS. I worked on building web pages and creating responsive web design, ensuring that the content displays correctly across different devices. The course introduced me to techniques for creating modern websites and allowed me to create static web pages that are well-structured and visually appealing."
      },
    postgreSQLInfo: {
        bg: "В курса по работа с бази данни научих как да манипулирам и съхранявам данни ефективно. Изучих агрегация на данни в PostgreSQL и как да работя с релации между таблици, за да оптимизирам базата данни. Научих се да използвам процедури и функции, за да автоматизирам операции върху данни, и да управлявам транзакции за постигане на консистентност и целостта на данните в приложението.",
        de: "Im Kurs über die Arbeit mit Datenbanken habe ich gelernt, wie man Daten effizient manipuliert und speichert. Ich habe die Aggregation von Daten in PostgreSQL studiert und gelernt, wie man mit Beziehungen zwischen Tabellen arbeitet, um die Datenbank zu optimieren. Ich habe auch gelernt, wie man Prozeduren und Funktionen verwendet, um Datenoperationen zu automatisieren, und wie man Transaktionen verwaltet, um Konsistenz und Integrität der Daten in der Anwendung zu gewährleisten.",
        en: "In the course on working with databases, I learned how to manipulate and store data effectively. I studied data aggregation in PostgreSQL and how to work with relationships between tables to optimize the database. I also learned to use procedures and functions to automate data operations and manage transactions to ensure data consistency and integrity in the application."
      },
    pythonORMInfo: {
        bg: "В курса по работа с бази данни чрез ORM научих как да създавам и управлявам модели и миграции. Научих се да извличам и манипулирам данни от бази данни, като използвам релации между различни модели за ефективно свързване на данни. Изследвах къстамизация и оптимизация на модели, за да подобря производителността на приложението. Курсът обхвана и по-сложни техники при работа със заявки чрез ORM, което ми позволи да пиша по-ефективен и мащабируем код.",
        de: "Im Kurs über die Arbeit mit Datenbanken über ORM habe ich gelernt, wie man Modelle und Migrationen erstellt und verwaltet. Ich habe gelernt, wie man Daten aus Datenbanken abruft und manipuliert und dabei Beziehungen zwischen verschiedenen Modellen für eine effiziente Verknüpfung von Daten verwendet. Ich habe mich mit der Anpassung und Optimierung von Modellen beschäftigt, um die Leistung der Anwendung zu verbessern. Der Kurs deckte auch fortgeschrittene Techniken für die Arbeit mit ORM-Abfragen ab, die es mir ermöglichten, effizienteren und skalierbaren Code zu schreiben.",
        en: "In the course on working with databases through ORM, I learned how to create and manage models and migrations. I gained the ability to extract and manipulate data from databases while using relationships between different models for efficient data linking. I explored customization and optimization of models to improve application performance. The course also covered advanced techniques for working with ORM queries, enabling me to write more efficient and scalable code."
      },
    pythonOOPInfo:{
        bg: "В курса по Python OOP изучих основните принципи: инкапсулация, наследяване, полиморфизъм и абстракция. Създавах класове и обекти, изграждах йерархии от класове и прилагах наследяване. Разгледах и функционално програмиране чрез ламбда функции, итератори, генератори и декоратори, за да разширя функционалността на кода.",
        de: "Im Python OOP-Kurs habe ich die grundlegenden Prinzipien gelernt: Kapselung, Vererbung, Polymorphie und Abstraktion. Ich habe Klassen und Objekte erstellt, Klassenhierarchien aufgebaut und Vererbung angewendet. Außerdem habe ich funktionale Programmierung mit Lambda-Funktionen, Iteratoren, Generatoren und Decorators verwendet, um die Funktionalität des Codes zu erweitern.",
        en: "In the Python OOP course, I learned the core principles: encapsulation, inheritance, polymorphism, and abstraction. I created classes and objects, built class hierarchies, and applied inheritance. I also explored functional programming with lambda functions, iterators, generators, and decorators to enhance the functionality of the code."
      },
    pythonBasicInfo: {
        en: 'In this course, I am gaining fundamental programming knowledge and skills. I am learning how to use functions, and how to work with for and while loops to effectively manage program logic.',
        de: 'In diesem Kurs erwerbe ich grundlegende Programmierkenntnisse und -fähigkeiten. Ich lerne, wie man Funktionen verwendet und mit for- und while-Schleifen arbeitet, um die Logik in Programmen effektiv zu steuern.',
        bg: 'В този курс придобивам основни знания и умения в програмирането. Научавам се да използвам функции, както и да работя с for и while цикли за ефективно управление на логиката в програмите.',
    },
    pythonFundamentalsInfo: {
        en: 'In this course, I deepened my understanding of fundamental programming concepts, such as working with arrays, data structures, and algorithms. This solid foundation provided the groundwork for my further professional development and enabled me to solve complex problems more efficiently.',
        de: 'In diesem Kurs vertiefte ich mein Verständnis in fundamentalen Programmierkonzepten, wie der Arbeit mit Arrays, Datenstrukturen und Algorithmen. Diese solide Basis legte den Grundstein für meine weitere fachliche Entwicklung und befähigte mich, komplexe Probleme effizienter zu lösen.',
        bg: 'В този курс задълбочих знанията си по основни програмни концепции като работа с масиви, структури от данни и алгоритми. Тази солидна основа положи началото на моето по-нататъшно професионално развитие и ми позволи да решавам сложни проблеми по-ефективно.',
    },
    pythonAdvancedInfo: {
        en: 'n this course, I deepened my understanding of fundamental programming concepts, including working with Stacks and Queues, Tuples, Sets, multidimensional lists, and Matrices. Additionally, I expanded my knowledge in advanced functions, error handling, and file handling. This solid foundation helped me efficiently manage complex data structures such as Matrices and develop algorithms, laying the groundwork for my further professional growth.',
        de: 'In diesem Kurs vertiefte ich mein Verständnis in fundamentalen Programmierkonzepten, einschließlich der Arbeit mit Stacks and Queues, Tuples, Sets, multidimensionalen Listen und Matrizen. Darüber hinaus erweiterte ich mein Wissen in fortgeschrittenen Funktionen, Fehlerbehandlung und Dateiverarbeitung. Diese solide Basis half mir, komplexe Datenstrukturen wie Matrizen effizient zu verwalten und Algorithmen zu entwickeln, was eine Grundlage für meine weitere fachliche Entwicklung bildete.',
        bg: 'В този курс задълбочих разбирането си за основни програмни концепции, включително работа със Stacks and Queues, Tuples, Sets, многомерни списъци и матрици. Освен това разширих познанията си в областта на разширените функции, обработката на грешки и работата с файлове. Тази солидна основа ми помогна да управлявам ефективно сложни структури от данни като матрици и да разработвам алгоритми, като положи основата за моето по-нататъшно професионално развитие.',
    },
};

export default translateCertifictes;