name: Build and Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
          cache: 'npm'
          cache-dependency-path: ./my-favorites/package-lock.json

      - name: Install npm dependencies
        run: npm ci
        working-directory: ./my-portfolio

      - name: Build client
        run: npm run build
        working-directory: ./my-portfolio

      - name: Deploy to Render
       
        
          -H "Authorization: Bearer $RENDER_API_KEY" \
          -H "Content-Type: application/json" \
          -d '{"branch": "main"}'
